blank_issues_enabled: false
contact_links:
  - name: Latest releases
    url: https://www.curseforge.com/wow/addons/dialogueui/files
    about: Check that you are on the latest version before reporting a bug.
